"""empty message

Revision ID: 07e3cca57fb6
Revises: d6bc929bcee9
Create Date: 2026-05-28 22:13:57.950959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e3cca57fb6'
down_revision = 'd6bc929bcee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
