"""empty message

Revision ID: 09a81af9293a
Revises: ab9492af08ca
Create Date: 2026-05-18 12:31:51.142269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a81af9293a'
down_revision = 'ab9492af08ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timer_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('timer_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('timer_status')
        batch_op.drop_column('timer_started_at')

    # ### end Alembic commands ###
