"""empty message

Revision ID: 2a656696722a
Revises: 07e3cca57fb6
Create Date: 2026-06-23 10:24:42.258222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a656696722a'
down_revision = '07e3cca57fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_miles', sa.Numeric(precision=5, scale=1), nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('delivery_miles')

    # ### end Alembic commands ###
