"""empty message

Revision ID: 3c1a7e303148
Revises: 26233d755e1e
Create Date: 2026-04-24 10:23:08.332556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c1a7e303148'
down_revision = '26233d755e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_item_user_key'))
        batch_op.drop_column('user_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_key', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_cart_item_user_key'), ['user_key'], unique=False)

    # ### end Alembic commands ###
