"""empty message

Revision ID: 41420472e34d
Revises: 3c1a7e303148
Create Date: 2026-04-24 11:22:47.372537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41420472e34d'
down_revision = '3c1a7e303148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_snapshot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.drop_column('cart_snapshot')

    # ### end Alembic commands ###
