"""empty message

Revision ID: 451edfd4dcae
Revises: 454bd1f15d86
Create Date: 2026-04-24 12:23:05.971851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451edfd4dcae'
down_revision = '454bd1f15d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('shipping_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('total')
        batch_op.drop_column('tax')
        batch_op.drop_column('shipping_fee')
        batch_op.drop_column('subtotal')

    # ### end Alembic commands ###
