"""empty message

Revision ID: 454bd1f15d86
Revises: 41420472e34d
Create Date: 2026-04-24 12:13:42.854127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454bd1f15d86'
down_revision = '41420472e34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line_2', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.drop_column('address_line_2')

    # ### end Alembic commands ###
