"""empty message

Revision ID: 5cbc7cd7935d
Revises: e8ae2fdbab92
Create Date: 2026-05-03 15:26:17.279855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbc7cd7935d'
down_revision = 'e8ae2fdbab92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
