"""empty message

Revision ID: 9bc4245be477
Revises: d5ac731d6e14
Create Date: 2026-04-19 16:43:39.713387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc4245be477'
down_revision = 'd5ac731d6e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_key', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_cart_user_key'), ['user_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_user_key'))
        batch_op.drop_column('user_key')

    # ### end Alembic commands ###
