"""empty message

Revision ID: d5ac731d6e14
Revises: 10855eed2f13
Create Date: 2026-04-19 15:57:05.547657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ac731d6e14'
down_revision = '10855eed2f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_key', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_cart_item_user_key'), ['user_key'], unique=False)

    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_key', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_checkout_draft_user_key'), ['user_key'], unique=False)

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_key', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_wishlist_user_key'), ['user_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_user_key'))
        batch_op.drop_column('user_key')

    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkout_draft_user_key'))
        batch_op.drop_column('user_key')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_item_user_key'))
        batch_op.drop_column('user_key')

    # ### end Alembic commands ###
