"""empty message

Revision ID: e8ae2fdbab92
Revises: 451edfd4dcae
Create Date: 2026-04-24 15:11:22.943462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ae2fdbab92'
down_revision = '451edfd4dcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_address_line_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('billing_address_line_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('billing_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('same_as_delivery', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_draft', schema=None) as batch_op:
        batch_op.drop_column('same_as_delivery')
        batch_op.drop_column('billing_postal_code')
        batch_op.drop_column('billing_state')
        batch_op.drop_column('billing_city')
        batch_op.drop_column('billing_address_line_2')
        batch_op.drop_column('billing_address_line_1')

    # ### end Alembic commands ###
